name: Check GitHub Contributions and Notify

on:
  schedule:
    - cron: "0 * * * *" # UTC時間で毎日13時（日本時間で21時）に実行

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Check for Contributions on Public Repositories and Count Repository Creations
        id: check_contributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ユーザー名を取得
          USERNAME="${{ github.repository_owner }}"

          # GraphQLクエリでpublicリポジトリのコミット数とリポジトリ作成数を取得
          QUERY="{\"query\": \"query { user(login: \\\"$USERNAME\\\") { contributionsCollection { commitContributionsByRepository { repository { name, isPrivate, defaultBranchRef { name } } contributions(first: 100) { totalCount } } repositoryContributions(first: 100) { totalCount } } } }\"}"

          # GitHub APIリクエストとエラーハンドリング
          RESPONSE=$(curl -H "Authorization: bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -d "$QUERY" https://api.github.com/graphql || { echo 'GitHub APIリクエストに失敗しました'; exit 1; })

          echo "Response: $RESPONSE"

          # publicなリポジトリのコミット数をカウント
          MAIN_COUNT=$(echo $RESPONSE | jq '[.data.user.contributionsCollection.commitContributionsByRepository[] | select(.repository.defaultBranchRef.name == "main" and .repository.isPrivate == false) | .contributions.totalCount] | add // 0')
          MASTER_COUNT=$(echo $RESPONSE | jq '[.data.user.contributionsCollection.commitContributionsByRepository[] | select(.repository.defaultBranchRef.name == "master" and .repository.isPrivate == false) | .contributions.totalCount] | add // 0')

          # 作成されたpublicリポジトリの数を取得
          REPO_CREATION_COUNT=$(echo $RESPONSE | jq '.data.user.contributionsCollection.repositoryContributions.totalCount')

          # コミット数とリポジトリ作成数の合計を計算
          TOTAL_COUNT=$(($MAIN_COUNT + $MASTER_COUNT + $REPO_CREATION_COUNT))

          # 結果を表示
          echo "Total contributions to main and master (public only): $TOTAL_COUNT"
          echo "Public repository creations: $REPO_CREATION_COUNT"

          # 詳細な結果を表示
          echo "Commit counts per repository (public only):"
          echo $RESPONSE | jq '.data.user.contributionsCollection.commitContributionsByRepository[] | select(.repository.isPrivate == false) | {repo: .repository.name, branch: .repository.defaultBranchRef.name, count: .contributions.totalCount}'

          # コミット数またはリポジトリ作成数が0の場合、通知を送信
          if [ "$TOTAL_COUNT" -eq 0 ]; then
            echo "今日の貢献がありません。通知を送信します。"
            echo "CONTRIBUTIONS_COUNT=$TOTAL_COUNT" >> $GITHUB_ENV
          fi

      - name: Send LINE Notification if No Contributions
        if: env.CONTRIBUTIONS_COUNT == '0'
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          MESSAGE: "まもなく今日が終わりますがまだGitHubの草が生えてません！今すぐ草を生やしましょう！"
        run: |
          curl -X POST -H "Authorization: Bearer $LINE_TOKEN" -F "message=$MESSAGE" https://notify-api.line.me/api/notify
